server-ip=127.0.0.1
server-port=25585
online-mode=false
enforce-secure-profile=false
spawn-protection=0
max-players=1
view-distance=2
simulation-distance=2
level-type=minecraft:flat
generator-settings={"layers":[{"block":"minecraft:bedrock","height":1},{"block":"minecraft:dirt","height":2},{"block":"minecraft:grass_block","height":1}],"biome":"minecraft:plains"}
sync-chunk-writes=false
pause-when-empty-seconds=-1
max-tick-time=120000
